# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtw6v-EyDU_seKqVAzysbxRV6cSa3yLA
"""

import random

# ==========================================
# CONSTANTS & CONFIGURATION
# ==========================================
BOARD_SIZE = 8
POPULATION_SIZE = 100
MUTATION_RATE = 0.05
MAX_GENERATIONS = 1000

# Maximum non-attacking pairs on an 8x8 board is 8C2 = 28
MAX_FITNESS = (BOARD_SIZE * (BOARD_SIZE - 1)) // 2  # 28


# ==========================================
# 1. AI MODULE FUNCTIONS (Genetic Algorithm)
# ==========================================

def create_individual():
    """
    Creates a single individual (chromosome).
    Represented as an array of 8 integers where index is the column
    and value is the row position of the queen (0 to 7).
    """
    return [random.randint(0, BOARD_SIZE - 1) for _ in range(BOARD_SIZE)]


def fitness_score(individual):
    """
    Fitness Function: Calculates how many non-attacking queen pairs exist.
    Max fitness = 28 (0 attacking pairs = solution).
    """
    clashes = 0
    for i in range(BOARD_SIZE):
        for j in range(i + 1, BOARD_SIZE):
            # Check for horizontal line attacks (row match)
            if individual[i] == individual[j]:
                clashes += 1
            # Check for diagonal attacks
            elif abs(individual[i] - individual[j]) == abs(i - j):
                clashes += 1

    return MAX_FITNESS - clashes


def selection(population, fitnesses):
    """
    Fitness-Proportional Selection (Roulette Wheel Selection).
    Selects one parent based on relative fitness score.
    """
    total_fitness = sum(fitnesses)
    probabilities = [f / total_fitness for f in fitnesses]
    return random.choices(population, weights=probabilities, k=1)[0]


def crossover(parent1, parent2):
    """
    Single-Point Crossover: Combines two parents to create an offspring.
    """
    crossover_point = random.randint(1, BOARD_SIZE - 2)
    child = parent1[:crossover_point] + parent2[crossover_point:]
    return child


def mutate(individual):
    """
    Mutation: Randomly alters a queen's row position with a small probability.
    """
    for i in range(BOARD_SIZE):
        if random.random() < MUTATION_RATE:
            individual[i] = random.randint(0, BOARD_SIZE - 1)
    return individual


# ==========================================
# 2. HELPER & VISUALIZATION FUNCTIONS
# ==========================================

def print_board(individual):
    """
    Renders the ASCII chessboard showing the placement of 8 Queens.
    """
    print("\n  " + "---" * BOARD_SIZE)
    for row in range(BOARD_SIZE):
        line = "| "
        for col in range(BOARD_SIZE):
            if individual[col] == row:
                line += "Q  "
            else:
                line += ".  "
        print(line + "|")
    print("  " + "---" * BOARD_SIZE)


# ==========================================
# 3. MAIN EXECUTION & GA LOOP
# ==========================================

def solve_8_queens():
    # Step 1: Initialize random population
    population = [create_individual() for _ in range(POPULATION_SIZE)]

    print("=== Solving 8-Queens using Genetic Algorithm (AI Module) ===")

    for generation in range(1, MAX_GENERATIONS + 1):
        # Calculate fitness for all individuals
        fitnesses = [fitness_score(ind) for ind in population]

        # Check if a perfect solution is found
        if MAX_FITNESS in fitnesses:
            best_idx = fitnesses.index(MAX_FITNESS)
            solution = population[best_idx]

            print(f"\n[SUCCESS] Solution found in Generation {generation}!")
            print(f"Queen positions (Column -> Row): {solution}")
            print(f"Fitness Score: {fitness_score(solution)} / {MAX_FITNESS}")

            print_board(solution)
            return solution

        # Step 2: Breed new generation
        new_population = []
        for _ in range(POPULATION_SIZE):
            parent1 = selection(population, fitnesses)
            parent2 = selection(population, fitnesses)
            child = crossover(parent1, parent2)
            child = mutate(child)
            new_population.append(child)

        population = new_population

        if generation % 100 == 0 or generation == 1:
            best_fit = max(fitnesses)
            print(f"Generation {generation:4d} | Max Fitness: {best_fit}/{MAX_FITNESS}")

    print("\n[FAILED] Max generations reached without finding an optimal solution.")
    return None


if __name__ == "__main__":
    solve_8_queens()