# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtw6v-EyDU_seKqVAzysbxRV6cSa3yLA
"""

import heapq
import math

# ==========================================
# CONFIGURATION & CONSTANTS
# ==========================================
# Grid Map: 0 = Free Cell, 1 = Obstacle/Wall
GRID = [
    [0, 0, 0, 0, 0, 0, 0],
    [0, 1, 1, 1, 1, 1, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 1, 1, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 0, 0]
]

START_POS = (0, 0)  # Top-Left corner
GOAL_POS = (4, 5)   # Bottom-Right region


# ==========================================
# 1. NODE & HEURISTIC DEFINITION
# ==========================================

class Node:
    """Represents a state node in the A* search tree."""
    def __init__(self, position, parent=None, g_cost=0, h_cost=0):
        self.position = position  # Tuple (row, col)
        self.parent = parent      # Reference to parent node for path reconstruction
        self.g_cost = g_cost      # Exact cost from start to current node
        self.h_cost = h_cost      # Estimated cost from current node to goal
        self.f_cost = g_cost + h_cost  # f(n) = g(n) + h(n)

    def __lt__(self, other):
        """Comparator for Priority Queue (Min-Heap based on f_cost)."""
        return self.f_cost < other.f_cost


def euclidean_heuristic(pos_a, pos_b):
    """
    Heuristic function h(n): Straight-line Euclidean distance to goal.
    Admissible and consistent heuristic for 2D grids.
    """
    return math.sqrt((pos_a[0] - pos_b[0]) ** 2 + (pos_a[1] - pos_b[1]) ** 2)


# ==========================================
# 2. A* SEARCH ALGORITHM
# ==========================================

def solve_a_star(grid, start, goal):
    rows = len(grid)
    cols = len(grid[0])

    # Priority Queue for Open Set (Nodes to be evaluated)
    open_set = []

    # Dictionary tracking best g_cost for visited nodes
    open_dict = {}
    closed_set = set()

    # Create start node
    start_node = Node(start, parent=None, g_cost=0, h_cost=euclidean_heuristic(start, goal))
    heapq.heappush(open_set, start_node)
    open_dict[start] = start_node.g_cost

    # Valid relative movements (Up, Down, Left, Right)
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    print("=== A* Search Algorithm (Informed AI Pathfinding) ===")
    print(f"Start Position: {start} | Goal Position: {goal}\n")

    nodes_explored = 0

    while open_set:
        # Step 1: Pop the node with the lowest f(n) score
        current_node = heapq.heappop(open_set)
        nodes_explored += 1

        if current_node.position in open_dict:
            del open_dict[current_node.position]

        # Goal Test
        if current_node.position == goal:
            path = []
            curr = current_node
            while curr:
                path.append(curr.position)
                curr = curr.parent
            path.reverse()

            print(f"[SUCCESS] Goal reached! Path found in {len(path) - 1} steps.")
            print(f"Total Nodes Explored: {nodes_explored}")
            print(f"Path Sequence: {path}\n")
            return path

        closed_set.add(current_node.position)

        # Step 2: Expand neighbors
        r, c = current_node.position
        for dr, dc in directions:
            neighbor_pos = (r + dr, c + dc)

            # Check boundary conditions and wall obstacles
            if not (0 <= neighbor_pos[0] < rows and 0 <= neighbor_pos[1] < cols):
                continue
            if grid[neighbor_pos[0]][neighbor_pos[1]] == 1:  # Obstacle
                continue
            if neighbor_pos in closed_set:
                continue

            tentative_g = current_node.g_cost + 1  # Step cost = 1
            h_val = euclidean_heuristic(neighbor_pos, goal)

            # Check if this path to neighbor is better than any previous one
            if neighbor_pos not in open_dict or tentative_g < open_dict[neighbor_pos]:
                neighbor_node = Node(neighbor_pos, current_node, tentative_g, h_val)
                heapq.heappush(open_set, neighbor_node)
                open_dict[neighbor_pos] = tentative_g

    print("[FAILED] No valid path exists to the goal position.")
    return None


# ==========================================
# 3. GRID VISUALIZATION
# ==========================================

def display_grid_with_path(grid, path):
    """Prints ASCII representation of Grid map with the computed shortest path."""
    path_set = set(path) if path else set()
    print("Map Visualization ('S'=Start, 'G'=Goal, '*'=Path, 'X'=Wall, '.'=Free):")
    print("  " + "---" * len(grid[0]))

    for r in range(len(grid)):
        line = "| "
        for c in range(len(grid[0])):
            pos = (r, c)
            if pos == START_POS:
                line += "S  "
            elif pos == GOAL_POS:
                line += "G  "
            elif pos in path_set:
                line += "*  "
            elif grid[r][c] == 1:
                line += "X  "
            else:
                line += ".  "
        print(line + "|")
    print("  " + "---" * len(grid[0]))


# ==========================================
# MAIN EXECUTION
# ==========================================

if __name__ == "__main__":
    solution_path = solve_a_star(GRID, START_POS, GOAL_POS)
    if solution_path:
        display_grid_with_path(GRID, solution_path)