# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtw6v-EyDU_seKqVAzysbxRV6cSa3yLA
"""

from collections import deque

# ==========================================
# 1. AI GRAPH SEARCH AGENT (BFS)
# ==========================================

class GraphBFS:
    def __init__(self):
        # Adjacency List representation of the graph
        self.graph = {}

    def add_edge(self, u, v):
        """Adds a directed edge from node u to node v."""
        if u not in self.graph:
            self.graph[u] = []
        if v not in self.graph:
            self.graph[v] = []
        self.graph[u].append(v)

    def bfs_traversal(self, start_node):
        """
        Performs standard BFS traversal from a start node.
        Visits all nodes level-by-level.
        """
        visited = set()
        queue = deque([start_node])
        visited.add(start_node)

        traversal_order = []

        while queue:
            # Dequeue a vertex from front of queue
            current_node = queue.popleft()
            traversal_order.append(current_node)

            # Get all adjacent vertices of current_node
            for neighbor in self.graph.get(current_node, []):
                if neighbor not in visited:
                    visited.add(neighbor)
                    queue.append(neighbor)

        return traversal_order

    def bfs_shortest_path(self, start_node, target_node):
        """
        Finds the shortest path between start_node and target_node using BFS.
        Returns the path as a list of nodes.
        """
        if start_node not in self.graph or target_node not in self.graph:
            return None

        # Queue stores tuples of (current_node, path_taken)
        queue = deque([(start_node, [start_node])])
        visited = set([start_node])

        while queue:
            current_node, path = queue.popleft()

            # Goal Test
            if current_node == target_node:
                return path

            # Expand Neighbors
            for neighbor in self.graph.get(current_node, []):
                if neighbor not in visited:
                    visited.add(neighbor)
                    queue.append((neighbor, path + [neighbor]))

        return None  # No path found


# ==========================================
# 2. MAIN EXECUTION & EXAMPLE
# ==========================================

if __name__ == "__main__":
    g = GraphBFS()

    # Constructing an example graph:
    # 0 -> 1, 0 -> 2
    # 1 -> 3, 1 -> 4
    # 2 -> 4, 2 -> 5
    # 3 -> 5
    g.add_edge(0, 1)
    g.add_edge(0, 2)
    g.add_edge(1, 3)
    g.add_edge(1, 4)
    g.add_edge(2, 4)
    g.add_edge(2, 5)
    g.add_edge(3, 5)

    start = 0
    goal = 5

    print("=== Breadth-First Search (BFS) Implementation ===")

    # 1. Full Traversal
    order = g.bfs_traversal(start)
    print(f"BFS Traversal starting from node {start}: {order}")

    # 2. Shortest Path Finding
    path = g.bfs_shortest_path(start, goal)
    if path:
        print(f"Shortest Path from {start} to {goal}: {' -> '.join(map(str, path))}")
    else:
        print(f"No path exists between {start} and {goal}.")