# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtw6v-EyDU_seKqVAzysbxRV6cSa3yLA
"""

import itertools

# ==========================================
# AI CSP SOLVER (Cryptarithmetic)
# ==========================================

class CryptarithmeticSolver:
    def __init__(self, word1, word2, result):
        self.word1 = word1.upper()
        self.word2 = word2.upper()
        self.result = result.upper()

        # Unique letters across all words
        self.letters = list(set(self.word1 + self.word2 + self.result))

        # Letters that cannot be 0 (first letter of any word)
        self.first_letters = {self.word1[0], self.word2[0], self.result[0]}

    def _word_to_number(self, word, letter_map):
        """Converts a word to its numerical value using the assigned letter map."""
        return sum(letter_map[char] * (10 ** idx) for idx, char in enumerate(reversed(word)))

    def solve(self):
        """
        Solves the cryptarithmetic puzzle using backtracking and permutation matching
        over the state space of digits (0-9).
        """
        if len(self.letters) > 10:
            print("[ERROR] A cryptarithmetic problem cannot contain more than 10 unique letters.")
            return None

        print("=== Cryptarithmetic Problem Solver (AI CSP Agent) ===")
        print(f"Equation: {self.word1} + {self.word2} = {self.result}")
        print(f"Unique Variables (Letters): {self.letters} (Count: {len(self.letters)})\n")

        digits = range(10)
        solutions_found = 0

        # Generate permutations of digits for the unique letters
        for p in itertools.permutations(digits, len(self.letters)):
            letter_map = dict(zip(self.letters, p))

            # Constraint 1: Leading letters cannot be zero
            if any(letter_map[char] == 0 for char in self.first_letters):
                continue

            num1 = self._word_to_number(self.word1, letter_map)
            num2 = self._word_to_number(self.word2, letter_map)
            res = self._word_to_number(self.result, letter_map)

            # Constraint 2: Addition equality (word1 + word2 == result)
            if num1 + num2 == res:
                solutions_found += 1
                print(f"[SUCCESS] Solution #{solutions_found} Found:")
                print(f"  Mapping: {letter_map}")
                print(f"  {self.word1:>6}  ->  {num1:>6}")
                print(f"+ {self.word2:>6}  ->  +{num2:>6}")
                print(f"  {'-'*6}      {'-'*6}")
                print(f"  {self.result:>6}  ->  {res:>6}\n")

        if solutions_found == 0:
            print("[FAILED] No valid digit assignments exist for this puzzle.")

        return solutions_found


# ==========================================
# MAIN EXECUTION
# ==========================================

if __name__ == "__main__":
    # Standard Classic Problem: SEND + MORE = MONEY
    solver = CryptarithmeticSolver(word1="SEND", word2="MORE", result="MONEY")
    solver.solve()