# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtw6v-EyDU_seKqVAzysbxRV6cSa3yLA
"""

from collections import deque

# ==========================================
# AI GRAPH SEARCH AGENT (DFS)
# ==========================================

class GraphDFS:
    def __init__(self):
        # Adjacency List representation of the graph
        self.graph = {}

    def add_edge(self, u, v):
        """Adds a directed edge from node u to node v."""
        if u not in self.graph:
            self.graph[u] = []
        if v not in self.graph:
            self.graph[v] = []
        self.graph[u].append(v)

    # --------------------------------------
    # 1. RECURSIVE DFS TRAVERSAL
    # --------------------------------------
    def dfs_recursive(self, start_node, visited=None, traversal_order=None):
        """
        Performs DFS traversal recursively starting from a node.
        """
        if visited is None:
            visited = set()
        if traversal_order is None:
            traversal_order = []

        # Mark node as visited and record order
        visited.add(start_node)
        traversal_order.append(start_node)

        # Recur for all adjacent unvisited vertices
        for neighbor in self.graph.get(start_node, []):
            if neighbor not in visited:
                self.dfs_recursive(neighbor, visited, traversal_order)

        return traversal_order

    # --------------------------------------
    # 2. ITERATIVE DFS USING LIFO STACK
    # --------------------------------------
    def dfs_iterative(self, start_node):
        """
        Performs DFS traversal iteratively using an explicit Stack.
        """
        visited = set()
        stack = [start_node]
        traversal_order = []

        while stack:
            # Pop a vertex from top of stack
            current_node = stack.pop()

            if current_node not in visited:
                visited.add(current_node)
                traversal_order.append(current_node)

                # Push neighbors to stack (reversed to visit left-to-right order)
                for neighbor in reversed(self.graph.get(current_node, [])):
                    if neighbor not in visited:
                        stack.append(neighbor)

        return traversal_order

    # --------------------------------------
    # 3. PATH FINDING USING DFS (Backtracking)
    # --------------------------------------
    def dfs_find_path(self, start_node, target_node, path=None, visited=None):
        """
        Finds a path from start_node to target_node using DFS with backtracking.
        """
        if visited is None:
            visited = set()
        if path is None:
            path = [start_node]

        visited.add(start_node)

        # Goal Test
        if start_node == target_node:
            return path

        for neighbor in self.graph.get(start_node, []):
            if neighbor not in visited:
                new_path = self.dfs_find_path(neighbor, target_node, path + [neighbor], visited)
                if new_path is not None:
                    return new_path

        return None  # Return None if no path found in this branch


# ==========================================
# MAIN EXECUTION & EXAMPLE
# ==========================================

if __name__ == "__main__":
    g = GraphDFS()

    # Constructing an example directed graph:
    # 0 -> 1, 0 -> 2
    # 1 -> 3, 1 -> 4
    # 2 -> 5
    # 4 -> 5
    g.add_edge(0, 1)
    g.add_edge(0, 2)
    g.add_edge(1, 3)
    g.add_edge(1, 4)
    g.add_edge(2, 5)
    g.add_edge(4, 5)

    start = 0
    goal = 5

    print("=== Depth-First Search (DFS) Implementation ===")

    # 1. Recursive DFS Traversal
    rec_order = g.dfs_recursive(start)
    print(f"DFS Traversal (Recursive) starting from {start}: {rec_order}")

    # 2. Iterative DFS Traversal
    iter_order = g.dfs_iterative(start)
    print(f"DFS Traversal (Iterative) starting from {start}: {iter_order}")

    # 3. Path Finding
    path = g.dfs_find_path(start, goal)
    if path:
        print(f"DFS Path from {start} to {goal}: {' -> '.join(map(str, path))}")
    else:
        print(f"No path exists between {start} and {goal}.")