# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11m4bRFNqaYEBNl8ABGxJrkGpEa9V1G_E
"""

import numpy as np

# Activation functions and their derivatives
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    # Derivative where x is already sigmoid(z)
    return x * (1 - x)

class FeedforwardNeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size, learning_rate=0.1):
        self.learning_rate = learning_rate

        # Initialize weights randomly with mean 0
        self.W1 = np.random.randn(input_size, hidden_size)
        self.b1 = np.zeros((1, hidden_size))

        self.W2 = np.random.randn(hidden_size, output_size)
        self.b2 = np.zeros((1, output_size))

    def forward(self, X):
        """Passes input X forward through the network."""
        self.z1 = np.dot(X, self.W1) + self.b1
        self.a1 = sigmoid(self.z1)  # Hidden layer activation

        self.z2 = np.dot(self.a1, self.W2) + self.b2
        self.a2 = sigmoid(self.z2)  # Output layer activation
        return self.a2

    def backward(self, X, y, output):
        """Calculates gradients using Chain Rule and updates weights."""
        m = X.shape[0]  # Number of samples

        # 1. Output Layer Error & Gradient
        error_output = output - y
        delta_output = error_output * sigmoid_derivative(output)

        dW2 = np.dot(self.a1.T, delta_output) / m
        db2 = np.sum(delta_output, axis=0, keepdims=True) / m

        # 2. Hidden Layer Error & Gradient
        error_hidden = np.dot(delta_output, self.W2.T)
        delta_hidden = error_hidden * sigmoid_derivative(self.a1)

        dW1 = np.dot(X.T, delta_hidden) / m
        db1 = np.sum(delta_hidden, axis=0, keepdims=True) / m

        # 3. Update Weights and Biases (Gradient Descent)
        self.W2 -= self.learning_rate * dW2
        self.b2 -= self.learning_rate * db2
        self.W1 -= self.learning_rate * dW1
        self.b1 -= self.learning_rate * db1

    def train(self, X, y, epochs=10000):
        for epoch in range(epochs):
            output = self.forward(X)
            self.backward(X, y, output)

            if (epoch + 1) % 2000 == 0:
                loss = np.mean(np.square(y - output))  # Mean Squared Error
                print(f"Epoch {epoch + 1}/{epochs} - Loss: {loss:.6f}")


# ================= Example Usage (XOR Problem) =================
if __name__ == "__main__":
    # Inputs (4 samples, 2 features)
    X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])

    # Expected Outputs (XOR gate)
    y = np.array([
        [0],
        [1],
        [1],
        [0]
    ])

    # Instantiate NN: 2 Inputs -> 4 Hidden Neurons -> 1 Output
    nn = FeedforwardNeuralNetwork(input_size=2, hidden_size=4, output_size=1, learning_rate=0.5)

    print("Training Neural Network on XOR Data...")
    nn.train(X, y, epochs=10000)

    # Make Predictions
    predictions = nn.forward(X)
    print("\nFinal Predictions:")
    for i in range(len(X)):
        print(f"Input: {X[i]} -> Target: {y[i][0]} -> Predicted: {predictions[i][0]:.4f} (Rounded: {round(predictions[i][0])})")