# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtw6v-EyDU_seKqVAzysbxRV6cSa3yLA
"""

from collections import deque

# ==========================================
# CONFIGURATION
# ==========================================
# State Representation: (M_left, C_left, Boat_position)
# Boat_position: 1 = Left Bank, 0 = Right Bank
INITIAL_STATE = (3, 3, 1)
GOAL_STATE = (0, 0, 0)
BOAT_CAPACITY = 2


# ==========================================
# AI SEARCH AGENT (BFS)
# ==========================================

def is_valid_state(state):
    """
    Checks if a state violates constraints:
        1. Counts must be within valid range [0, 3].
        2. Cannibals must never outnumber Missionaries on EITHER bank (if M > 0).
    """
    m_left, c_left, _ = state
    m_right = 3 - m_left
    c_right = 3 - c_left

    # Bounds check
    if not (0 <= m_left <= 3 and 0 <= c_left <= 3):
        return False

    # Left bank check
    if m_left > 0 and c_left > m_left:
        return False

    # Right bank check
    if m_right > 0 and c_right > m_right:
        return False

    return True


def get_possible_moves(state):
    """
    Generates all valid next states based on boat moves (1 or 2 passengers).
    """
    m_left, c_left, boat = state
    next_states = []

    # All possible combinations of passengers in the boat: (missionaries, cannibals)
    # Boat can carry 1 or 2 total people
    moves = []
    for m_boat in range(BOAT_CAPACITY + 1):
        for c_boat in range(BOAT_CAPACITY + 1):
            if 0 < m_boat + c_boat <= BOAT_CAPACITY:
                moves.append((m_boat, c_boat))

    for m_boat, c_boat in moves:
        if boat == 1:  # Moving Left -> Right
            new_state = (m_left - m_boat, c_left - c_boat, 0)
            action_desc = f"Send {m_boat} Missionary(ies) & {c_boat} Cannibal(s) to Right"
        else:          # Moving Right -> Left
            new_state = (m_left + m_boat, c_left + c_boat, 1)
            action_desc = f"Return {m_boat} Missionary(ies) & {c_boat} Cannibal(s) to Left"

        if is_valid_state(new_state):
            next_states.append((new_state, action_desc))

    return next_states


def solve_missionaries_cannibals():
    """
    Solves the problem using BFS to find the shortest path of boat transfers.
    """
    queue = deque([(INITIAL_STATE, [])])
    visited = set([INITIAL_STATE])

    print("=== Missionaries and Cannibals Problem (AI BFS Search) ===")
    print(f"Initial State: {INITIAL_STATE[0]} Missionaries, {INITIAL_STATE[1]} Cannibals on Left Bank")
    print(f"Goal: Move all safely to Right Bank\n")

    while queue:
        current_state, path = queue.popleft()

        # Goal Test
        if current_state == GOAL_STATE:
            print(f"[SUCCESS] Solution found in {len(path)} moves!\n")

            # Formatting Output
            print(f"Start  : Left ({INITIAL_STATE[0]}M, {INITIAL_STATE[1]}C) | Right (0M, 0C)")
            for idx, (action, (m_l, c_l, b)) in enumerate(path, 1):
                m_r, c_r = INITIAL_STATE[0] - m_l, INITIAL_STATE[1] - c_l
                boat_side = "Left" if b == 1 else "Right"
                print(f"Move {idx:2d}: {action:<48} -> Left ({m_l}M, {c_l}C) | Right ({m_r}M, {c_r}C) [Boat: {boat_side}]")
            return path

        # State Expansion
        for next_state, action in get_possible_moves(current_state):
            if next_state not in visited:
                visited.add(next_state)
                queue.append((next_state, path + [(action, next_state)]))

    print("[FAILED] No solution found.")
    return None


if __name__ == "__main__":
    solve_missionaries_cannibals()