# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtw6v-EyDU_seKqVAzysbxRV6cSa3yLA
"""

import random
import time

# ==========================================
# CONFIGURATION & CONSTANTS
# ==========================================
GRID_SIZE = 3          # 3x3 Grid (9 total squares)
INITIAL_BATTERY = 20   # Maximum actions the vacuum can perform
CLEAN_REWARD = 10      # Score gained for cleaning dirt
MOVE_COST = 1          # Battery cost per movement action


# ==========================================
# 1. ENVIRONMENT CLASS
# ==========================================
class VacuumEnvironment:
    def __init__(self, size=GRID_SIZE):
        self.size = size
        # Randomly dirty ~50% of the grid locations
        self.grid = {
            (r, c): random.choice(["Dirty", "Clean"])
            for r in range(size) for c in range(size)
        }
        # Ensure at least one cell is dirty to start
        if all(val == "Clean" for val in self.grid.values()):
            self.grid[(0, 0)] = "Dirty"

    def is_dirty(self, location):
        return self.grid[location] == "Dirty"

    def clean_location(self, location):
        self.grid[location] = "Clean"

    def display_grid(self, agent_pos):
        """Displays ASCII visualization of the room and agent."""
        print("\n  " + "+---" * self.size + "+")
        for r in range(self.size):
            row_str = "  |"
            for c in range(self.size):
                cell = (r, c)
                state = "D" if self.grid[cell] == "Dirty" else " "
                if cell == agent_pos:
                    row_str += f"[V]|"  # V represents Vacuum
                else:
                    row_str += f" {state} |"
            print(row_str)
            print("  " + "+---" * self.size + "+")


# ==========================================
# 2. AI REFLEX AGENT WITH MODEL
# ==========================================
class IntelligentReflexAgent:
    def __init__(self, grid_size=GRID_SIZE):
        self.grid_size = grid_size
        self.position = (0, 0)
        self.battery = INITIAL_BATTERY
        self.score = 0

        # Internal Model: Tracks visited status and environment memory
        self.visited = set([self.position])

    def perceive(self, environment):
        """Sensory percept: Is the current cell dirty?"""
        return environment.is_dirty(self.position)

    def select_next_move(self):
        """
        Heuristic movement policy:
        Prioritizes moving to adjacent unvisited cells first.
        """
        r, c = self.position
        neighbors = [
            (r - 1, c),  # Up
            (r + 1, c),  # Down
            (r, c - 1),  # Left
            (r, c + 1)   # Right
        ]
        # Filter valid grid positions
        valid_neighbors = [
            pos for pos in neighbors
            if 0 <= pos[0] < self.grid_size and 0 <= pos[1] < self.grid_size
        ]

        # 1. Prefer unvisited neighbors (exploration)
        unvisited = [pos for pos in valid_neighbors if pos not in self.visited]
        if unvisited:
            return random.choice(unvisited)

        # 2. Otherwise pick any valid neighbor randomly
        if valid_neighbors:
            return random.choice(valid_neighbors)

        # If no valid moves (shouldn't happen in a connected grid), stay put
        return self.position

    def act(self, environment):
        """
        AI Decision Cycle (Perceive -> Decide -> Act).
        Returns True if active, False if powered down.
        """
        if self.battery <= 0:
            print("\n[AGENT] Battery depleted! Powering down.")
            return False

        is_dirty = self.perceive(environment)

        if is_dirty:
            # Action: Suck Dirt
            environment.clean_location(self.position)
            self.score += CLEAN_REWARD
            print(f"[ACTION] Cleaned dirt at location {self.position} (+{CLEAN_REWARD} pts)")
        else:
            # Action: Move to adjacent space
            new_pos = self.select_next_move()
            if new_pos != self.position: # Only print move if actually moved
                print(f"[ACTION] Moved from {self.position} -> {new_pos}")
                self.position = new_pos
                self.visited.add(new_pos)
            else:
                print(f"[ACTION] Staying at {self.position} (no new unvisited neighbors)")

        self.battery -= MOVE_COST
        return True


# ==========================================
# 3. MAIN SIMULATION LOOP
# ==========================================
def run_vacuum_world():
    env = VacuumEnvironment(GRID_SIZE)
    agent = IntelligentReflexAgent(GRID_SIZE)

    print("=== Vacuum Cleaner World (Model-Based AI Agent) ===")
    print(f"Grid Size: {GRID_SIZE}x{GRID_SIZE} | Starting Battery: {INITIAL_BATTERY}")

    step = 0
    while True:
        step += 1
        print(f"\n--- Step {step} | Battery Left: {agent.battery} | Score: {agent.score} ---")
        env.display_grid(agent.position)

        # Check Termination: Environment completely clean
        if all(val == "Clean" for val in env.grid.values()):
            print("\n[SUCCESS] Entire environment is clean!")
            break

        # Run Agent Action step
        active = agent.act(env)
        if not active:
            break
        time.sleep(0.5) # Small delay for better visualization

    print("\n=== Final Results ===")
    print(f"Total Steps Taken : {step}")
    print(f"Final Performance Score : {agent.score}")
    print(f"Remaining Battery : {agent.battery}")


if __name__ == "__main__":
    run_vacuum_world()