# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtw6v-EyDU_seKqVAzysbxRV6cSa3yLA
"""

from collections import deque

# ==========================================
# CONFIGURATION
# ==========================================
JUG1_CAPACITY = 3  # Capacity of Jug 1 in Liters
JUG2_CAPACITY = 4  # Capacity of Jug 2 in Liters
TARGET_AMOUNT = 2  # Target water amount required


# ==========================================
# AI SEARCH AGENT (BFS)
# ==========================================

def get_next_states(state):
    """
    Generates all valid successor states from the current state (j1, j2)
    using the allowed water jug rules/actions.
    """
    j1, j2 = state
    next_states = []

    # Rule 1: Fill Jug 1 completely
    next_states.append(((JUG1_CAPACITY, j2), "Fill Jug 1 (3L)"))

    # Rule 2: Fill Jug 2 completely
    next_states.append(((j1, JUG2_CAPACITY), "Fill Jug 2 (4L)"))

    # Rule 3: Empty Jug 1
    next_states.append(((0, j2), "Empty Jug 1"))

    # Rule 4: Empty Jug 2
    next_states.append(((j1, 0), "Empty Jug 2"))

    # Rule 5: Pour Jug 1 into Jug 2 until Jug 2 is full or Jug 1 is empty
    pour_1_to_2 = min(j1, JUG2_CAPACITY - j2)
    next_states.append(((j1 - pour_1_to_2, j2 + pour_1_to_2), "Pour Jug 1 -> Jug 2"))

    # Rule 6: Pour Jug 2 into Jug 1 until Jug 1 is full or Jug 2 is empty
    pour_2_to_1 = min(j2, JUG1_CAPACITY - j1)
    next_states.append(((j1 + pour_2_to_1, j2 - pour_2_to_1), "Pour Jug 2 -> Jug 1"))

    return next_states


def solve_water_jug_bfs():
    """
    Solves the Water Jug problem using Uninformed AI Search (BFS).
    Guarantees finding the optimal path with minimum steps.
    """
    initial_state = (0, 0)

    # Queue stores: (current_state, path_taken)
    queue = deque([(initial_state, [])])

    # Set to keep track of visited states to avoid infinite loops
    visited = set([initial_state])

    print("=== Water Jug Problem Solver (AI BFS Agent) ===")
    print(f"Jug 1 Capacity: {JUG1_CAPACITY}L | Jug 2 Capacity: {JUG2_CAPACITY}L")
    print(f"Goal State: Measure {TARGET_AMOUNT} Liters of water\n")

    while queue:
        (j1, j2), path = queue.popleft()

        # Goal Test: Check if either jug contains the target amount
        if j1 == TARGET_AMOUNT or j2 == TARGET_AMOUNT:
            print(f"[SUCCESS] Solution found in {len(path)} steps!\n")
            print(f"Step 0: Initial State -> (Jug 1: 0L, Jug 2: 0L)")

            for step_num, (action, state) in enumerate(path, 1):
                print(f"Step {step_num}: {action:<22} -> (Jug 1: {state[0]}L, Jug 2: {state[1]}L)")
            return path

        # Expand node: Generate valid child states
        for next_state, action in get_next_states((j1, j2)):
            if next_state not in visited:
                visited.add(next_state)
                queue.append((next_state, path + [(action, next_state)]))

    print("[FAILED] No solution possible with given parameters.")
    return None


if __name__ == "__main__":
    solve_water_jug_bfs()